image:
  file: .Dockerfile

#Tasks here are the specific installation of this site, while the Dockerfile is a general Drupal LAMP stack
tasks:
  - init: |
      sudo mysql -e "CREATE DATABASE IF NOT EXISTS drupal"
      composer install
      sudo cp conf/drupal.settings.php web/sites/default/settings.php
      vendor/drush/drush/drush -y site-install minimal --existing-config
      vendor/drush/drush/drush -y content-sync:import
    command: |
      apachectl start

ports:
  - port: 8001
    onOpen: open-browser
  - port: 8828
    onOpen: ignore
  - port: 8829
    onOpen: ignore
  - port: 3306
    onOpen: ignore

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: true

vscode:
  extensions:
    - eamodio.gitlens
    - skippednote.VS-code-drupal
    - gitlab.gitlab-workflow
    - cweijan.vscode-mysql-client2
    - esbenp.prettier-vscode
    - gruntfuggly.todo-tree
    - mblode.twig-language
    - vscode-icons-team.vscode-icons
