_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: e4b8738c-2f53-4e27-9d1d-aa138462a1ec
name: 'Ryan Robinson''s Test Site'
mail: ryan@alliterationapplications.com
slogan: 'For use in Drupal functionality testing'
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
